### ISSUE TITLE
Unused query-string dependency fails dependency check

### ISSUE THREAD

**Issue by darrylmorton-digicatapult** [pbeshai/use-query-params#107]
npm run depcheck fails with the following message:

`
Unused dependencies
* query-string
`

I expected query-string to be used dependency as it doesn't appear to be optional?

**Comment by pbeshai** [comment]
Probably because it is used via `serialize-query-params` and not `use-query-params` directly

**Comment by mattdean-digicatapult** [comment]
Should it be listed as a `peerDependency` then?

**Comment by fbarl** [comment]
I just tripped over this as well and ended up chasing a bug for 2 hours as I apparently needed to explicitly add `query-string` for my app to work since `yarn` wouldn't pick it up from the current dep tree :confused: 

I'm no expert but it seems that there are at least 2 viable solutions:

1. Add `query-string` to _dependencies_ in `serialize-query-params` (as opposed to _peerDependencies_ where it is list now) and remove it from the _devDependencies_ here - IMO this would be the simplest solution
2. Move `query-string` to _peerDependencies_ here in `use-query-params` to make sure the condition gets passed along to the consumers of `use-query-params` and to remove the dependency check error above

**Comment by pbeshai** [comment]
No worries, if there's a better way I'm happy to do it. npm is always spitting out a million warnings so it's hard to notice any that will actually have an impact, at least in my experience.

**Comment by pbeshai** [comment]
FYI after some discussion in #127 I've made it so an exception is thrown if query-string is missing or an invalid version is found in dev. While this still keeps query-string as a peer dependency of serialize-query-params and not of use-query-params directly, I think it should help catch this common error more quickly. Closing this issue for now. If someone can explain why query-string should also be a peer dependency of use-query-params in addition to serialize-query-params, I'm happy to learn and update.

**Comment by bstro** [comment]
I keep getting this error in my create-react-app:
`Error: serialize-query-params requires query-string ^5.1.1 || ^6, but 4.3.4 is installed. Note: you may also see this message if you're using use-query-params.`

I receive this error whether the latest `query-string` is added as a dependency or not. I also throws this error if I add it as a peer dependency. My project is a monorepo using yarn workspaces.
