### ISSUE TITLE
replace is default UrlUpdateType not pushIn

### ISSUE THREAD

**Issue by RufusK** [pbeshai/use-query-params#120]
hello, awesome library that i use very intensly! thans for the hard work everybody!

however here is a little problem i have: 
without giving anything as a second argument to useQueryParam it always replaces the history no matter if i use a custom history or BrowserRouter from react-router-dom. if i give "pushIn" as the second argument it works as expected. so i assume the default seems to be "replace" or "replaceIn" instead of "pushIn".
i looked into the source code and saw that pushIn is default in createLocationWithChanges so now i don't know wether its my environment or the lib that is doing something wrong
each way i think having to put the UrlUpdateType in every setValue isnt very DRY. this should be configurable in the QueryParamProvider

i use:
"use-query-params": "^1.1.6", (also tried with 0.6.0)
"react-router-dom": "^5.2.0",

**Comment by RufusK** [comment]
i just saw that the bug can be easily seen in the official demo page: https://peterbeshai.com/use-query-params/

pressing the first setFoo button (with no second parameter) works like replacing (back button wont work)
the last button however works as expected.

**Comment by pbeshai** [comment]
The code on the website is pretty far out of date actually. If you can reproduce your problem in a CodeSandbox, I'd be happy to investigate, but the default has been pushIn for a while now. I'd guess something else is missing with your setup, but would need to see a reproducible example to help. 

Instead of providing a configuration param, you can get around having a different default by using your own wrapper hook as described in https://github.com/pbeshai/use-query-params/issues/109.
