### ISSUE TITLE
withDefault - Should it update the url with default query params?

### ISSUE THREAD

**Issue by cristian-eriomenco** [pbeshai/use-query-params#138]
Suppose we have a page with the following path:`/products`
On initial render there is a category select with a **default value** of: `On Sale`

**products.tsx**
```
  const [query, setQuery] = useQueryParams({
    category: withDefault(String, "On Sale")
  });
  ...
  return <>
  ...
       {query.category} // On Sale
  ...
  </>
```
At this stage the url will still be /products even though, conceptually there is a query string assumed like `?category=On%20Sale`

I know I could just have an effect like:
```
// Sync default QueryString with url
useEffect(() => {
    setQuery(query);
},[])
```
But: 
1. It would mean too much boilerplate
2. It would result in an unnecessary re-render (might be router specific I'm using Next.js)

However maybe make it as an optional feature aka: `withSyncDefault(....)` ?

What do you think?

**Comment by pbeshai** [comment]
Hi there, the community is somewhat divided on this. Some insist default parameters should get auto-populated, some insist when parameters are equal to their defaults they should be removed. 

If you want to avoid a re-render, you'll have to modify the URL directly without using your router system, which may cause other issues. For example by using `window.history.replaceState(undefined, undefined, '/products?category=On%20Sale')`. Seems to me it's safer to just have a re-render and do something similar to your useEffect type.

Something along these lines would reduce the boilerplate to a single spot:

```js
const useQueryParamsWithDefaults = (queryConfig) => {
  const [query, setQuery] = useQueryParams(queryConfig);

  const defaultsToForce = computeNeededDefaults(query, queryConfig);

  useEffect(() => {
    setQuery(defaultsToForce)
  }, [defaultsToForce])

  return [query, setQuery]
}
```

I have been thinking over some new things to add for a v2 early next year and I do want to address some of the issues around defaults there, perhaps we'll end up with support for both approaches.

**Comment by zxjon22** [comment]
Long time user of https://ui-router.github.io/ for AngularJS here, migrating to React.

ui-router has something called 'squash' when you configure your parameters. When it updates the URL, it removes (squashes) any parameters whose current values matches the defaults.

So, I guess it would be something like:
```js
  const [qs, setQueryParams] = useQueryParams({
    p: withDefault(NumberParam, 1, true /* squash */),
    q: withDefault(StringParam, '', true /* squash */)
  });
```
This tends to produce tidier URLs (just IMO, of course).

**Comment by tonymj76** [comment]
i don't fully understand `withDefault` i though it helps to set a default value to the URL param??

**Comment by dietergeerts** [comment]
I'm just using this library to replace custom code. I also used `ui-router` a lot the past years, which is a fantastic routing library.

@tonymj76, when checking out the code, the `withDefault` will only apply a default when reading the query param, and having that decoded to `undefined` (or `null` depending on the option).

`ui-router` also has a default param option, so that on decode, the default value is used when there was no query param provided.

Now like @zxjon22 is mentioning, `ui-router` also has the `squash` option, which will not add the query param to the url when it's the default value.

With routers like `ui-router`, even when you don't use the `squash` option, you don't have any problem with default values, because `ui-router` itself is in control of the query, meaning that when initially there was no query param provided, it will be filled in by the router. _(This is one of the many reason `react-router` is really not a good router, as much functionality has to be add on top of by the consumer, and these functionalities are all common for many apps.)_

So because of the combination of react-route rand this library, it's impossible to automatically update the url with the default params if they were not provided (or at least very hard with a lot of side-effects). So I would propose that instead of trying to do this, that the `withDefault` adds a `squash` option, so that the behavior is consistent, meaning that initially, there was no provided value, and when then updating with the same config, there will also no query param added because it's the default. That way, the consumer of these packages don't need to OR update the url themselves initially, OR add custom code to actually squash the query param.

I hope what I'm telling here makes sense?

**Comment by jrnail23** [comment]
@pbeshai, you said earlier in this discussion:
> Some insist default parameters should get auto-populated, some insist when parameters are equal to their defaults they should be removed.

I'm in the latter group... how can I make sure that my defaults get removed?

**Comment by dietergeerts** [comment]
@pbeshai , you can try this:

```
const [query, setQuery] = useQueryParams({
  sort: withSquashedDefault(PatientSortColumnParam, defaultSort),
  query: withSquashedDefault(StringParam, ''),
  filter: withSquashedDefault(createEnumParam(patientFilters), defaultFilter),
})
```

```
import { QueryParamConfig, withDefault } from 'use-query-params'
import _flow from 'lodash/fp/flow'
import _isEqual from 'lodash/fp/isEqual'

/**
 * Uses default value when query param is nullable and hides it from the search.
 *
 * @see {@link https://github.com/pbeshai/use-query-params/issues/138}
 */
export function withSquashedDefault<T, Default extends NonNullable<T>>(
  paramConfig: QueryParamConfig<T>,
  defaultValue: Default,
): QueryParamConfig<T, NonNullable<T> | Default> {
  const defaulted = withDefault(paramConfig, defaultValue)

  return {
    encode: _flow(
      (value) => (_isEqual(value, defaultValue) ? undefined : value),
      defaulted.encode,
    ),
    decode: defaulted.decode,
  }
}
```

**Comment by pbeshai** [comment]
Hi there, this has been partially solved in v2.0.0-rc.0  via the `removeDefaultsFromUrl` option. Give it a try and let me know if you run into issues. See the [changelog](https://github.com/pbeshai/use-query-params/blob/master/packages/use-query-params/CHANGELOG.md#migrating-from-v1) for details.

**Comment by jrnail23** [comment]
@pbeshai, I haven't tried it yet, but thanks for this update!  This looks like it's going to address several issues I've had.

**Comment by nemethricsi** [comment]
> Suppose we have a page with the following path:`/products` On initial render there is a category select with a **default value** of: `On Sale`
> 
> **products.tsx**
> 
> ```
>   const [query, setQuery] = useQueryParams({
>     category: withDefault(String, "On Sale")
>   });
>   ...
>   return <>
>   ...
>        {query.category} // On Sale
>   ...
>   </>
> ```
> 
> At this stage the url will still be /products even though, conceptually there is a query string assumed like `?category=On%20Sale`
> 
> I know I could just have an effect like:
> 
> ```
> // Sync default QueryString with url
> useEffect(() => {
>     setQuery(query);
> },[])
> ```
> 
> But:
> 
> 1. It would mean too much boilerplate
> 2. It would result in an unnecessary re-render (might be router specific I'm using Next.js)
> 
> However maybe make it as an optional feature aka: `withSyncDefault(....)` ?
> 
> What do you think?

@cristian-eriomenco Was your original issue solved? I'm not quite sure how to populate the default values to the URL without useEffect.
