### ISSUE TITLE
Adding types similar to to useState

### ISSUE THREAD

**Issue by vvav3** [pbeshai/use-query-params#141]
Hi. I want to do something like this:

```
type TabKey = 'key1' | 'key2';
const [tab, setTab] = useQueryParam<TabKey>('tab', StringParam);
```

Is it possible to do without typecasting?

**Comment by pbeshai** [comment]
We just added createEnumParam in serialize-query-params 1.3.0 to make this less work (and also make non supported values decode as undefined):

```ts
import { createEnumParam } from 'serialize-query-params';

// values other than 'asc' or 'desc' will be decoded as undefined
const TabKeyParam = createEnumParam(['key1', 'key2'])
```

In theory you should be able to import it from use-query-params after updating to 1.3.0 but I may need to publish a new version of UQP to get the dependencies to automatically work so let me know.

Historically I just did this:

```ts
type TabKey = 'key1' | 'key2';
const TabKeyParam = StringParam as QueryParamConfig<
  TabKey | null | undefined,
  TabKey | undefined
>;
```
then used it as

```ts
const [tab, setTab] = useQueryParam('tab', TabKeyParam)
```

**Comment by robinvw1** [comment]
@pbeshai nice addition! I just tried it out:

![image](https://user-images.githubusercontent.com/793157/106289087-1d619080-6249-11eb-9711-1727e7220822.png)


As you can see, `profile` is typed as `"offensive" | null | undefined`.

Because I'm using `withDefault` it would be cool if the `null` and `undefined` types are removed and only `"offensive"` remained.

**Comment by pbeshai** [comment]
Hmm yes that is strange, since withDefault resolves correctly with StringParam. Perhaps the types for it can be improved, but I'm not sure how. The [code is here](https://github.com/pbeshai/serialize-query-params/blob/master/src/withDefault.ts), if you figure out a way for better type inference please feel free to PR. In the meantime, this will fix your problem:

```ts

type InvestmentProfile = 'offensive';
const InvestmentProfileParam = createEnumParam(['offensive']);

const TestComp = () => {
  const [query, setQuery] = useQueryParams({
    profile: withDefault(InvestmentProfileParam, 'offensive' as const), // <-- add as const
    profile2: withDefault(InvestmentProfileParam, 'offensive'),
  });
  const { profile, profile2 } = query;

  return null;
}
```

Then profile resolves:
![image](https://user-images.githubusercontent.com/793847/106298524-d653ab00-6208-11eb-8785-4817646f3022.png)


vs profile2:
![image](https://user-images.githubusercontent.com/793847/106298550-de134f80-6208-11eb-87fb-0925a69b9b51.png)


Example codesandbox here: https://codesandbox.io/s/recursing-lumiere-kwr6q?file=/src/App.tsx
