### ISSUE TITLE
query-string should be added to peer dependencies

### ISSUE THREAD

**Issue by slavafomin** [pbeshai/use-query-params#146]
Hello!

Thank you for this great library!

However, you should add `query-string` package to the `peerDependencies` field of the project's manifest, right now it's missing, however, it is a required transitive dependency.

Thanks!

**Comment by pbeshai** [comment]
Hi, there's been a few different issues on this (e.g., #107, #128), and it has been tricky to resolve. The short is use-query-params depends directly on serialize-query-params which has a peer dependency of query-string, it's not clear if it makes sense for use-query-params to also have it listed as a peer dep. In any case, the next major version of the lib will probably have a bring-your-own "query-string" option instead of depending on it directly (and likely use URLSearchParams as a default).

**Comment by fgblomqvist** [comment]
It does make sense for `use-query-params` to have it listed as a peer-dep since you directly depend on it:
https://github.com/pbeshai/use-query-params/blob/master/src/memoizedQueryParser.ts#L1
https://github.com/pbeshai/use-query-params/blob/master/src/helpers.ts#L2

While I'm looking forward to a future version that just uses URLSearchParams, it would be neat to get the peer dep in for this version. NPM 7 is supposed to automatically install peer deps but for some reason, it is not able to to dig deep enough to find that serialize-query-params needs `query-string`. I suspect it only checks direct dependencies.

**Comment by pbeshai** [comment]
I've added it as a peer dep now in v1.2.1
