### ISSUE TITLE
A way to check url size

### ISSUE THREAD

**Issue by thellimist** [pbeshai/use-query-params#154]
If really big objects are put as an argument to `useQueryParams`, the server returns `431 (Request Header Fields Too Large)` error. Is there a way in the library to handle this issue specifically while using hooks?

**Comment by pbeshai** [comment]
You'll need to compress whatever you're encoding in the URL to respect the max limits (I think around 2000 characters). If you're just encoding big JSON objects, you can create custom parameters that compress/decompress them to fit them more tersely in the URL. More fancy solutions involve things like storing a hash in elastic search or similar and using that in the URL, or trying to compress client-side with something like msgpack. These are out of scope of the library. 

An example custom parameter:

```js
import {
  decodeString,
} from 'use-query-params';

/** 
 * Map a custom object of form: 
 * {
 *    id: number,
 *    categories: string[],
 *    flag: boolean
 * }
 * to:
 * `${id}.${category}_${category}_${category}.${flag}`
 */
const MyParam = {
  encode: (input) => {
    if (input == null) return input;
    return `${input.id}.${input.categories.join('_')}.${input.flag ? 1 : 0}`
  },

  decode: (stringInput) => {
    // handle empty values and arrays with decodeString logic
    const str = decodeString(stringInput);
    if (str == null) return str;

    // split from our expected form
    const [idStr, categoryStr, flagStr] = str.split('.');

    return {
      // convert to number
      id: +idStr,
      // split into an array of strings
      categories: categoryStr.split('_'),
      // convert to boolean
      flag: flagStr === '1'
    }
  }
};
```

The above could be made even more terse by, for instance, using IDs instead of strings for categories and expanding/compressing those in the encode/decode functions.
