### ISSUE TITLE
"Unable to resolve dependency tree" with serialize-query-params & IE support

### ISSUE THREAD

**Issue by ddurden11** [pbeshai/use-query-params#172]
It is stated in the documentation that `use-query-params` has a peer dependency on `query-string` , and that to support IE 11 you must install v5.1.1. 

However, in my project ( where I need IE 11 support ) , I am getting a dependency tree error:

```
npm ERR! Found: query-string@5.1.1
npm ERR! node_modules/query-string
npm ERR!   query-string@"^5.1.1" from the root project
npm ERR!   peer query-string@"^5.1.1 || ^6 || ^7" from use-query-params@1.2.2
npm ERR!   node_modules/use-query-params
npm ERR!     use-query-params@"^1.2.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer query-string@"^7" from serialize-query-params@1.3.4
npm ERR! node_modules/use-query-params/node_modules/serialize-query-params
npm ERR!   serialize-query-params@"^1.3.3" from use-query-params@1.2.2
npm ERR!   node_modules/use-query-params
npm ERR!     use-query-params@"^1.2.2" from the root project
```

To me this looks like it is coming from `serialize-query-params` having a peer dependency on `query-string` v7.

Is this something that can be safely ignored with the `--legacy-peer-deps` flag, or is this package moving away from IE support?

*Update:* fixed incorrect version for `query-string` listed in error block

**Comment by pbeshai** [comment]
Hmm seems like something got overwritten when switching to the monorepo version. 5.1.1 should still work.

It used to read: 

```
    "query-string": "^5.1.1 || ^6 || ^7"
```

**Comment by dietergeerts** [comment]
@pbeshai , I looked into the history, and can't even find that it was used to read like that, not in the `serialize-query-param` package. And because of that, the latest version of `use-query-param` is a broken release, because it has a dependency tree that can't be achieved when using a peer of `query-string` lower than `7`.

Can this please be fixed and made sure it's tested and really works on those version? Because IE11 support is still a thing, and if these versions aren't fixed, and we can get no guarantee it will work on IE11, then this package can't be used for it.

_I don't want to be rude, so if I come over like that, I'm sorry. I also want to see IE11 go, but sadly that's not always an option_
