### ISSUE TITLE
`decodeNumber` not checking if value is a number anymore

### ISSUE THREAD

**Issue by chrisneven** [pbeshai/use-query-params#175]
Hi, thanks for the awesome library.

Today I upgraded to the newest version and noticed that I was getting some `isNaN` values. It seems that `decodeNumber` doesn't check on whether if it's a numeric value anymore: https://github.com/pbeshai/use-query-params/blob/a188792eb35c63feff0920746798bcd3910fd1dd/packages/serialize-query-params/src/serialize.ts#L212

Is this intended? If so, I'll probably need to create a custom paramconfig then.

Thanks in advance!

**Comment by pbeshai** [comment]
It does allow NaNs through, you're right. I don't think that behavior ever changed. I'm not sure exactly what the best thing for the library to do is since 

* `?foo` (undefined) 
* `?foo=` (null)
* `?foo=str` (NaN)
* `?foo=5` (5)

are all slightly different. Perhaps it is ideal for a NaN to be decoded as null or undefined but those values may be interpreted differently by user code at the moment (missing value vs bad value). Ideally creating a custom param is a low bar for users though. Here's a possible custom param you could use:

```js
import { encodeNumber, decodeNumber } from 'serialize-query-params'
 
const SafeNumberParam = {
  encode: encodeNumber,
  decode: function (input) {
    let result = decodeNumber(input)
    return Number.isNaN(result) ? null : result
  }
}
```

(note this I didn't test the above, but it should work)

**Comment by chrisneven** [comment]
Hi @pbeshai, that sounds reasonable! Thanks :)
