### ISSUE TITLE
Decoding objects with keys containing underscores breaks

### ISSUE THREAD

**Issue by jtheberge** [pbeshai/use-query-params#201]
`import { encodeObject, decodeObject, encodeString } from 'use-query-params';` 

`decodeObject(encodeObject({ a: 'b_c', d: 'e' }))` => `{a: 'b', c: undefined, d: 'e'}`
Also, encoding string does not fix this: `encodeString('b_c')` => `b_c`.

Is there a way to support underscores, or do I need to manually encode these characters inside keys?

**Comment by pbeshai** [comment]
You can just make your own ObjectParam:

```js
import {
  encodeObject,
  decodeObject
} from 'use-query-params';


const keyValueSeparator = '___' // default is "-"
const entrySeparator = '...' // default is "_"

const MyObjectParam = {
  encode: (obj) =>
    encodeObject(array, keyValueSeparator, entrySeparator),

  decode: (str) =>
    decodeObject(str, keyValueSeparator, entrySeparator)
};
```

See [serialize.ts](https://github.com/pbeshai/use-query-params/blob/master/packages/serialize-query-params/src/serialize.ts#L464) for other available functions.

Otherwise, you can just use a JsonParam. You may even consider creating your own param that uses [jsurl](https://github.com/Sage/jsurl) instead of the default `JSON.stringify` / `JSON.parse` setup.

**Comment by jtheberge** [comment]
Thank you @pbeshai  I did not notice these extra params!
