### ISSUE TITLE
Updating url is instant; can't call multiple useQueryParam set function

### ISSUE THREAD

**Issue by moonray** [pbeshai/use-query-params#53]
It would be great if useQueryParam behaved like useState where multiple calls to useState are batched. This way you could call the set function for useQueryParam multiple times (instead of having to use useQueryParams) without having the URL update between each call.

**Comment by TSMMark** [comment]
Without digging into any source code, on the surface this woulda like it should be pretty easy to implement right? 

Any maintainers want to post some pointers to get a potential contributer started moving in the right direction on this?

**Comment by patrickbenjamin1** [comment]
From my use currently, it does seem like you can call multiple `set` functions synchronously, and this will only trigger a single render, but currently each one acts as a separate push to the history stack meaning you can hit back through each one.

My feeling is that there should only be a single push for all `set` functions that are called synchronously so that this:

```
const [_, set1] = useQueryParam('key1', StringParam)
const [_, set2] = useQueryParam('key2', StringParam)

const run = () => {
   set1('value1')
   set2('value2')
}
```

would only cause a single rerender and a single history entry when run is called.

The desired effect can be achieved with the current implementation, however, by changing run to:

```
const run = () => {
   set1('value1')
   set2('value2', 'replaceIn')
}
```

I guess the issue with what I'm suggesting is that it would be hard to know what to do if the second argument is different between each call to different set functions - and as demonstrated, the behaviour I'm suggesting is possible with the current implementation.

**Comment by crubier** [comment]
Workaround:

```
  const [aa, setAa] = useQueryParam("aa", StringParam);
  const [bb, setBb] = useQueryParam("bb", StringParam);
  
  onClose={() => {
        setAa("aaaaa", "replaceIn");
        // Necessary to solve https://github.com/pbeshai/use-query-params/issues/53
        setTimeout(() => setBb("bbbbb", "replaceIn"), 1);
      }}
      
```

**Comment by pbeshai** [comment]
Hi there, happy to say this has been added in v2.0.0-rc.0 via the `enableBatching` option. It's a bit experimental in that I would have to rewrite all the tests to ensure it works exactly as expected, but from my cursor checks it works. Let me know if you experience issues with it in a new issue. See the [changelog](https://github.com/pbeshai/use-query-params/blob/master/packages/use-query-params/CHANGELOG.md#migrating-from-v1) for details.
