### ISSUE TITLE
How to add dynamic query params?

### ISSUE THREAD

**Issue by brianedelman** [pbeshai/use-query-params#72]
I have a situation where I need to define some pre-decided params and then we have some fields we are querying the backend by that belong in a JSONField. So the params can be totally dynamic. Everything else in my app is set up in a way to support that but since we define the param types on init, it doesn't look like that would be supported. Is there some way I am not seeing?

The quick fix is just to manually define the ones I know about, but would love to add them on the fly.
`const [query, setQuery] = useQueryParams({
    game: StringParam,
    platforms: CommaArrayParam,
    platform_mics: CommaArrayParam,
  });`

and would want to add something like `json_field__foo: Comma Array Param` as I need to query for it.

**Comment by pbeshai** [comment]
I think you can just modify what you pass into `useQueryParams`, it doesn't have to be the same every render.

**Comment by brianedelman** [comment]
So I don't think react handles this use case well. I tried an implementation of this and did some research but can't find anything specifically like what I am trying to do.

`const [jsonParams, setJsonParams] = useState([])
  const [query, setQuery] = useQueryParams({
    game: StringParam,
    platforms: CommaArrayParam,
    // dynamic json parameters
    ...jsonParams.reduce(function(result, item, index, array) {
      result[`game_details__${item}`] = CommaArrayParam;
      return result;
    }, {})
  });`
and then when i get a selected game later, I call setJsonParams
  `useEffect(() => {
      // NOTE: This sets json dynamic parameters to be absorbed by setQuery
      setJsonParams(['foo']);
  }, [selectedGames]);`

This returns the attached screenshot bug from react code. I don't know if they're just not handling this case or it's something not intended to be done. It feels a little like I am trying to do the equivalent of "this.state = 'foo'" to update state instead of "this.setState" but I don't know if that's really true.

I also tried using setQuery (which is my useQueryParams setter) like so 
`setQuery({
      game_details__foo: CommaArrayParam,
    })` 
before calling with actual values but that doesn't work either, which I didn't really expect it to but was just throwing stuff at the wall to see what stuck.

**Comment by dprgarner** [comment]
It looks like this library can't handle changing configs because there's code which breaks the [rules of hooks](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level).

There's code in useQueryParams which [calls hooks in a loop](https://github.com/pbeshai/use-query-params/blob/master/src/useQueryParams.ts#L78). This works in all the examples in the Readme as they all have static query params configs, but will break when the config passed into the `useQueryParams` hook changes. Hooks should always be called the same number of times and in the same order, so can't reliably be called in loops or conditionals. [Here's a codepen example](https://codesandbox.io/s/changing-params-configs-breaks-the-rules-of-hooks-969kv) with a changing config, which immediately blows up.

I don't think there will ever be a way for `useQueryParams` to dynamically call `useQueryParam` an arbitrary number of times, so some refactoring would be necessary there to support dynamic query params. I guess an interim solution would be for the documentation to make clear that query params configs must be static.

**Comment by pbeshai** [comment]
Thanks for pointing that out @dprgarner! I'll take a closer look.
