### ISSUE TITLE
useQueryParam - decodedValue has gets out of sync

### ISSUE THREAD

**Issue by jmcpeak** [pbeshai/use-query-params#78]
Can't use this library because it has a show stopper bug.

The dependency params for `const decodedValue = React.useMemo()` are wrong.

`arraySafeEncodedValue` isn't even used, only `encodedValue` which is _**not**_ in the list of dependencies.

This is almost always the wrong thing to do - `// eslint-disable-line react-hooks/exhaustive-deps`;

If you are accepting changes I'll make a PR for it...

**Comment by dprgarner** [comment]
Do you have an example where this fails to update? The dependency `arraySafeEncodedValue` is a derived variable, generated from `encodedValue` on every render, and _is_ in the dependencies of `useMemo`, so if `encodedValue` is changing but `arraySafeEncodedValue` is failing to change, then perhaps something's going wrong when generating `arraySafeEncodedValue`. 

[The code comments](https://github.com/guillaume/use-query-params/blob/master/src/useQueryParam.ts#L79) explain why this dependency is sufficient: it's to keep referential equality when the param is an array. I do share your concern about disabling react-hooks linting rules, though. There was a lot of [discussion on this issue](https://github.com/facebook/react/issues/14920) and the up-shot was that in almost all cases it was better to change the code rather than disable the linting rule.

**Comment by dprgarner** [comment]
I just [raised an issue](https://github.com/pbeshai/use-query-params/issues/82) about the setter functions not triggering renders. Perhaps this is the issue? You could confirm or rule this out by manually triggering a re-render with `useState` at the point where you were calling the param setter.

**Comment by jmcpeak** [comment]
> I just [raised an issue](https://github.com/pbeshai/use-query-params/issues/82) about the setter functions not triggering renders. Perhaps this is the issue? You could confirm or rule this out by manually triggering a re-render with `useState` at the point where you were calling the param setter.

Correct, that was the basics of it.

I have had to go write my own version of a query param hook for a variety of other reasons. When I finish it, I'll come back and share my version to see if can be of use.

**Comment by pbeshai** [comment]
I'm not sure I see the problem, if you're saying it is similar to what @dprgarner raised in #82, then it's because you don't have the QueryParamProvider added. 

The code in contention is just a way to do a shallow comparison with the previous array value. Yes it intentionally breaks the rule of hooks, but the alternative is just to hold on to the previous value myself and do a shallow comparison myself. The result of the code would be the same, I'm not sure how it is related to your issue of "decodedValue gets out of sync".

**Comment by pbeshai** [comment]
I reworked a bunch of the code today and released v1.0.0, which no longer violates the rules of hooks as far as I can tell.
